repos:
- repo: git://github.com/pre-commit/pre-commit-hooks
  rev: v0.9.5
  hooks:
    - id: check-ast
    - id: trailing-whitespace
    - id: check-byte-order-marker
    - id: check-case-conflict
    - id: check-executables-have-shebangs
    - id: check-json
    - id: check-yaml
    - id: check-symlinks
    - id: check-case-conflict
    - id: debug-statements
    - id: check-merge-conflict
    - id: detect-aws-credentials
    - id: detect-private-key
    - id: end-of-file-fixer
    - id: fix-encoding-pragma
    - id: mixed-line-ending
    - id: autopep8-wrapper
      args: ['-i',  '-j 4','--max-line-length=100', '-a']
#- repo: https://github.com/Lucas-C/pre-commit-hooks-nodejs
#  sha: v1.1.0
#  hooks:
#    - id: dockerfile_lint
- repo: git://github.com/Lucas-C/pre-commit-hooks
  rev: v1.1.5
  hooks:
    - id: remove-tabs
      exclude: Makefile
#- repo: git://github.com/detailyang/pre-commit-shell
#  rev: 1.0.2
#  hooks:
#    - id: shell-lint
#      files: run$
- repo: local
  hooks:
    - id: check-bash-syntax
      name: Check Shell scripts syntax corectness
      language: system
      entry: bash -n
      files: run$
