version: "3.3"
services:
  jefferson:
    restart: "no"
    image: "dpay/jefferson:release"
    ports:
      - "8080:8080"
      - "7777:7777"
    environment:
      JEFFERSON_REDIS_URL: redis://redis1:6379
      JEFFERSON_REDIS_READ_REPLICA_URLS: redis://redis2:6379
      JEFFERSON_STATSD_URL: statsd://statsd:8125
    env_file: .env
    volumes:
      - /root/jefferson/DEV_config.json:/app/DEV_config.json
  redis1:
    restart: "no"
    image: "redis:3.2"
  redis2:
    restart: "no"
    image: "redis:3.2"
    ports:
      - "6379:6379"
  statsd:
     restart: "no"
     image: "statsd"
     ports:
      - "8125:8125/udp"
